# Makefile.mingw
#
# Description: Top Makefile for pidgin-privacy-please.
#

.PHONY: all 

MINGW_MAKEFILE=Makefile.mingw

all:
	$(MAKE) -C prpltwtr -f $(MINGW_MAKEFILE) $@
	$(MAKE) -C gtkprpltwtr -f $(MINGW_MAKEFILE) $@

clean:
	$(MAKE) -C prpltwtr -f $(MINGW_MAKEFILE) $@
	$(MAKE) -C gtkprpltwtr -f $(MINGW_MAKEFILE) $@

installer: dist

dist:
	$(MAKE) -C prpltwtr -f $(MINGW_MAKEFILE) $@
	$(MAKE) -C gtkprpltwtr -f $(MINGW_MAKEFILE) $@
