void            pt_destroy (PurplePlugin * plugin);
void            pt_tooltip_text (PurpleBuddy * buddy, PurpleNotifyUserInfo * info, gboolean full);
GList          *pt_actions (PurplePlugin * plugin, gpointer context);
const char     *pt_list_icon (PurpleAccount * account, PurpleBuddy * buddy);
char           *pt_status_text (PurpleBuddy * buddy);
GList          *pt_status_types (PurpleAccount * account);
GList          *pt_blist_node_menu (PurpleBlistNode * node);
GList          *pt_chat_info (PurpleConnection * gc);
GHashTable     *pt_chat_info_defaults (PurpleConnection * gc, const char *chat_name);
void            pt_close (PurpleConnection * gc);
int             pt_send_im (PurpleConnection * gc, const char *conv_name, const char *message, PurpleMessageFlags flags);
void            pt_set_info (PurpleConnection * gc, const char *info);
void            pt_set_status (PurpleAccount * account, PurpleStatus * status);
void            pt_add_buddy (PurpleConnection * gc, PurpleBuddy * buddy, PurpleGroup * group);
void            pt_add_buddies (PurpleConnection * gc, GList * buddies, GList * groups);
void            pt_remove_buddy (PurpleConnection * gc, PurpleBuddy * buddy, PurpleGroup * group);
void            pt_remove_buddies (PurpleConnection * gc, GList * buddies, GList * groups);
void            pt_chat_join (PurpleConnection * gc, GHashTable * components);
void            pt_chat_leave (PurpleConnection * gc, int id);
int             pt_chat_send (PurpleConnection * gc, int id, const char *message, PurpleMessageFlags flags);
void            pt_get_cb_info (PurpleConnection * gc, int id, const char *who);
char           *pt_chat_get_name (GHashTable * components);
void            pt_convo_closed (PurpleConnection * gc, const gchar * conv_name);
void            pt_set_buddy_icon (PurpleConnection * gc, PurpleStoredImage * img);
void            pt_login (PurpleAccount * account);
void            pt_recoverable_disconnect (PurpleAccount * account, const char *message);
void            pt_disconnect (PurpleAccount * account, const char *message);
void            pt_verify_connection (PurpleAccount * account);
gboolean        pt_offline_message (const PurpleBuddy * buddy);
void            pt_api_get_info (PurpleConnection * gc, const char *username);
PurpleChat     *pt_blist_chat_find (PurpleAccount * account, const char *name);
